# Generated by Django 4.2.18 on 2025-03-07 18:15

import TopImotiVT.topimoti.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие')),
                ('property_type', models.CharField(choices=[('rent', 'Наем'), ('sale', 'Продажба')], max_length=50, verbose_name='Тип обява')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за кв.м.')),
                ('location', models.CharField(max_length=255, verbose_name='Град/Село')),
                ('district', models.CharField(max_length=255, verbose_name='Квартал')),
                ('area', models.PositiveIntegerField(verbose_name='Площ (кв.м.)')),
                ('floor', models.PositiveIntegerField(verbose_name='Етаж')),
                ('rooms', models.PositiveIntegerField(verbose_name='Брой стаи')),
                ('construction_type', models.CharField(choices=[('brick', 'Тухла'), ('panel', 'Панел'), ('monolithic', 'Монолит')], max_length=50, verbose_name='Вид строителство')),
                ('year_built', models.PositiveIntegerField(verbose_name='Година на завършване')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', validators=[TopImotiVT.topimoti.validators.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='topimoti.property')),
            ],
        ),
    ]
