# Generated by Django 4.2.18 on 2025-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topimoti', '0002_alter_property_construction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(verbose_name='Цена в евро'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_meter',
            field=models.IntegerField(verbose_name='Цена за кв.м.'),
        ),
    ]
