# Generated by Django 4.2.18 on 2025-03-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topimoti', '0003_alter_property_price_alter_property_price_per_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площ (кв.м.)'),
        ),
    ]
